### PR TITLE
Add models implementations

### PR DESCRIPTION
**Pull request by hohsiangwu**
Adding model implementations to models.py file. I have a couple questions accessing the model files.

In `get_embedding_model_path` function, what is the best way to access the model files in the relative directory, assuming that the setup.py file will download those files in the same openl3 folders?

How to test these function with the actual model weights file? Should I add those model weight files also to test folder so we can use for test? or it is sufficient that we only test the model architecture without the actual weights?

/cc @jtcramer @justinsalamon

### CODE REVIEW

**Comment by jtcramer** [comment]
Great thanks! Regarding your first point, I'd probably use `os.path.dirname(__file__)` to get at that directory. It might be a good idea though to put the models in a subdirectory. In copying the crepe code I didn't look too closely at where exactly it was putting the models, but if it's putting it in the openl3 module directory, we should probably put them in a subdirectory to avoid clutter. In that case, something like `os.path.join(os.path.dirname(__file__), 'models')` would be fine.

Regarding your second question, at least on Travis, the model files should be there upon installation. So for testing the build you should be able to just assume the models are there. If you wanted to test locally you'd need to download the model files to the expected places.

**Comment by hohsiangwu** [comment]
Updated, let me know if it looks okay, thanks!

**Comment by justinsalamon** [comment]
In case you're aren't doing it already, for local dev it can be convenient to use `pip install .` from the dev folder - this will install the repo using pip (which should download the models and place them where they should go on your local system), but will keep updating as the codebase is updated (since the pip installation points to the dev folder directly)

**Comment by hohsiangwu** [comment]
I am going to merge this PR since all the model parts are finished and tests are passing. There are some tests on the core failing, it might need to be addressed separately.

**Pull request merged**
