### PR TITLE
Fix API documentation and build

### PR DESCRIPTION
**Pull request by auroracramer**
Fix image embedding size in `load_image_embedding_model()` docstring, mock missing tensorflow.keras modules in `doc/conf.py` to fix API documentation build, and remove pin on sphinx version. Addresses #60 and #71.

### CODE REVIEW

**Comment by hohsiangwu** [comment]
Looks like the test failures are related to `import skimage` vs `import skimage.transform` as in [here](https://github.com/scikit-image/scikit-image/issues/4241)

Not sure if it is because skimage version is upgraded since we remove the limits on the version. Though why it's not failing in the previous build?

**Comment by hohsiangwu** [comment]
Except for the failing tests, other changes look good to me!

**Comment by auroracramer** [comment]
Thanks for taking a look into the build issues and finding this! I made an issue for it here: #73 and I'll merge in a fix to this branch.

**Comment by auroracramer** [comment]
As far why it didn't fail last time, it looks like it was because the last build to run was on May 29th, which was right before the travis-ci.org shutdown on May 31st. This repository was only recently migrated to travis-ci.com, so it looks that's why the change in skimage only appeared in this PR and when I renamed the main branch.

**Pull request merged**
